apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: soperator
  namespace: flux-system
spec:
  type: "oci"
  interval: 120m
  url: oci://cr.eu-north1.nebius.cloud/soperator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soperator-crds
  namespace: flux-system
spec:
  interval: 60m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: helm-soperator-crds
      sourceRef:
        kind: HelmRepository
        name: soperator
      interval: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soperator
  namespace: flux-system
spec:
  dependsOn:
    - name: ns
    - name: cert-manager
    - name: soperator-crds
  releaseName: soperator
  interval: 3m
  timeout: 3m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  targetNamespace: soperator-system
  chart:
    spec:
      chart: helm-soperator
      sourceRef:
        kind: HelmRepository
        name: soperator
      interval: 3m
  valuesFrom:
    - kind: ConfigMap
      name: soperator
      valuesKey: values.yaml
      optional: true
  values:
    controllerManager:
      manager:
        env:
          isPrometheusCrdInstalled: true
          isMariadbCrdInstalled: true
          isApparmorCrdInstalled: true
      kubeRbacProxy:
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.15.0
    certManager:
      enabled: true
