apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 120m
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  releaseName: mariadb-operator
  dependsOn:
    - name: cert-manager
  interval: 3m
  timeout: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  targetNamespace: mariadb-operator-system
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
      interval: 3m
  valuesFrom:
    - kind: ConfigMap
      name: mariadb-operator
      valuesKey: values.yaml
      optional: true
  values:
    webhook:
      enabled: true
      cert:
        certManager:
          enabled: true
