version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - gocheckcompilerdirectives
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - inamedparam
    - interfacebloat
    - nakedret
    - nosprintfhostport
    - predeclared
    - promlinter
    - tagalign
    - testableexamples
    - usestdlibvars
  disable:
    - depguard
    - dupl
    - errcheck
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - govet
    - ineffassign
    - lll
    - maintidx
    - misspell
    - mnd
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - staticcheck
    - tagliatelle
    - testpackage
    - unused
    - whitespace
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

output:
  formats:
    text:
      path: stdout

run:
  relative-path-mode: gomod
  allow-parallel-runners: true
  allow-serial-runners: true
