checks:
  manager:
    args:
      - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    env:
      slurmOperatorWatchNamespaces: '*'
    image:
      repository: cr.eu-north1.nebius.cloud/soperator/soperatorchecks
      tag: 1.18.3
    imagePullPolicy: Always
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
