---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: soperator-checks-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - slurm.nebius.ai
  resources:
  - slurmclusters
  verbs:
  - get
  - list
  - watch
