apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soperatorchecks.fullname" . }}-checks
  labels:
  {{- include "soperatorchecks.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.checks.serviceAccount.annotations | nindent 4 }}