apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm-logs
  namespace: flux-system
spec:
  interval: 120m
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-logs
  namespace: flux-system
spec:
  releaseName: logs
  interval: 3m
  timeout: 3m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  targetNamespace: logs-system
  chart:
    spec:
      chart: victoria-logs-single
      version: '0.9.*'
      sourceRef:
        kind: HelmRepository
        name: vm-logs
      interval: 3m
  valuesFrom:
    - kind: ConfigMap
      name: vm-logs
      valuesKey: values.yaml
      optional: true
  values:
    server:
      persistentVolume:
        enabled: true
        size: 10Gi
      vmServiceScrape:
        enabled: true
    vector:
      enabled: false
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"
