{{- if and .Values.rebooter.generateRBAC .Values.rebooter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodeconfigurator.name" . }}-sa
  {{- with include "nodeconfigurator.labels" . }}
  labels:
    {{- . | nindent 4 -}}
  {{- end }}
{{- end }}
