apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vm-stack
  namespace: flux-system
spec:
  interval: 120m
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-stack
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  targetNamespace: monitoring-system
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-operator
      valuesKey: values.yaml
      optional: true
  values:
    ## disable vm operator crds, managed separetly by gitops-crds repo
    crds:
      enabled: true
    victoria-metrics-operator:
      admissionWebhooks:
        enable: true
      crd:
        create: true
        cleanup:
          enabled: true
      operator:
        enable_converter_ownership: true
        disable_prometheus_converter: false
    kube-state-metrics:
      prometheusScrape: false
      selfMonitor:
        enabled: true
      vmServiceScrape:
        spec:
          endpoints:
            - port: http
              honorLabels: true
              metricRelabelConfigs:
                - action: labeldrop
                  regex: (uid|container_id|image_id)
            - port: metrics
              honorLabels: true
              metricRelabelConfigs:
                - action: labeldrop
                  regex: (uid|container_id|image_id)
          jobLabel: app.kubernetes.io/name
    grafana:
      assertNoLeakedSecrets: false
      sidecar:
        datasources:
          searchNamespace: ALL
        dashboards:
          searchNamespace: ALL
      plugins:
        - https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
        - victoriametrics-logs-datasource
    prometheus-node-exporter:
      enabled: true
    kubelet:
      enabled: true
    kubeProxy:
      enabled: true
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames: [kube-system]
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: http
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    defaultRules:
      rules:
        TooManyScrapeErrors:
          create: false
        TooHighChurnRate24h:
          create: false
        KubeHpaMaxedOut:
          create: false
        KubeMemoryOvercommit:
          create: false
      groups:
        etcd:
          create: false
        vmcluster:
          create: false
    vmsingle:
      spec:
        retentionPeriod: "30d"
        extraArgs:
          maxLabelsPerTimeseries: "40"
          search.maxUniqueTimeseries: "500000"
          dedup.minScrapeInterval: 30s
          search.maxQueryLen: "18765"
    vmagent:
      spec:
        extraArgs:
          promscrape.maxScrapeSize: "33554432"
    vmalert:
      enabled: false
    alertmanager:
      enabled: false
