apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: custom-supervisord-config
    namespace: soperator
    files:
      - supervisord.conf
    options:
      disableNameSuffixHash: true
  - name: slurm-epilog
    namespace: soperator
    files:
      - epilog.sh
    options:
      disableNameSuffixHash: true
  - name: slurm-prolog
    namespace: soperator
    files:
      - prolog.sh
    options:
      disableNameSuffixHash: true
