apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: custom-supervisord-config
    namespace: soperator
    files:
      - supervisord.conf
    options:
      disableNameSuffixHash: true
  - name: motd-nebius-o11y
    namespace: soperator
    files:
      - 95-nebius-o11y
    options:
      disableNameSuffixHash: true
  - name: image-storage
    namespace: soperator
    files:
      - daemon.json
      - enroot.conf
    options:
      disableNameSuffixHash: true
