apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: {{ include "son.rule.name" (dict "context" . "value" (include "son.rule.group.records" .)) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "son.labels" . | nindent 4 }}
spec:
  evaluationInterval: {{ include "son.alert.evaluationInterval" . }}
  datasource:
    url: {{ include "son.alert.dataSourceUrl" . | quote }}
  notifiers:
    - url: {{ "blackhole://" | quote }}
  ruleSelector:
    matchLabels:
      {{- include "son.rule.groupMatchLabel" (dict "context" . "value" (include "son.rule.group.records" .)) | nindent 6 }}

---

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: {{ include "son.rule.name" (dict "context" . "value" (include "son.rule.group.slack" .)) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "son.labels" . | nindent 4 }}
spec:
  evaluationInterval: {{ include "son.alert.evaluationInterval" . }}
  datasource:
    url: {{ include "son.alert.dataSourceUrl" . | quote }}
  notifiers:
    - url: {{ include "son.alertManager.url" . | quote}}
  ruleSelector:
    matchLabels:
      {{- include "son.rule.groupMatchLabel" (dict "context" . "value" (include "son.rule.group.slack" .)) | nindent 6 }}
