apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: security-profiles-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: soperator
---
apiVersion: v1
kind: Namespace
metadata:
  name: soperator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: logs-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
