apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bedag
  namespace: flux-system
spec:
  interval: 24h
  url: https://bedag.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ns
  namespace: flux-system
spec:
  interval: 60m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: raw
      sourceRef:
        kind: HelmRepository
        name: bedag
      interval: 3m
      version: 2.0.0
  install:
    remediation:
      retries: 3
  values:
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: mariadb-operator-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: security-profiles-operator-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: soperator
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: soperator-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: logs-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring-system
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager-system
