apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: custom-scripts
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    sconficontroller.slurm.nebius.ai: "true"
  annotations:
    sconficontroller.slurm.nebius.ai/path: "/opt/slurm_scripts"
data:
  cleanup_enroot.sh: |
{{ tpl (.Files.Get "custom_scripts/cleanup_enroot.sh") . | indent 4 }}

  map_job_dcgm.sh: |
{{ tpl (.Files.Get "custom_scripts/map_job_dcgm.sh") . | indent 4 }}

  unmap_job_dcgm.sh: |
{{ tpl (.Files.Get "custom_scripts/unmap_job_dcgm.sh") . | indent 4 }}

{{- if .Values.customScripts }}
{{- range $name, $content := .Values.customScripts }}
  {{ $name }}: |
{{ tpl $content $ | indent 4 }}
{{- end }}
{{- end }}
