apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 120m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: ns
    - name: prometheus-operator-crds
  interval: 3m
  timeout: 3m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  targetNamespace: cert-manager-system
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 3m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager
      valuesKey: values.yaml
      optional: true
  values:
    leaderElection:
      namespace: cert-manager-system
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
