apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-soperator
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.soperator.url }}
  type: {{ .Values.helmRepository.soperator.type }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-cert-manager
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.certManager.url }}
  type: {{ .Values.helmRepository.certManager.type }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-bedag
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.bedag.url }}
  type: {{ .Values.helmRepository.bedag.type }}
---
{{- if .Values.k8up.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-k8up
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.k8up.url }}
  type: {{ .Values.helmRepository.k8up.type }}
{{- end }}
---
{{- if .Values.mariadbOperator.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-mariadb-operator
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.mariadbOperator.url }}
  type: {{ .Values.helmRepository.mariadbOperator.type }}
{{- end }}
---
{{- if .Values.opentelemetry.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-opentelemetry-collector
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.opentelemetry.url }}
  type: {{ .Values.helmRepository.opentelemetry.type }}
{{- end }}
---
{{- if .Values.prometheusOperator.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-prometheus-operator-crds
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.prometheusOperator.url }}
  type: {{ .Values.helmRepository.prometheusOperator.type }}
{{- end }}
---
{{- if .Values.securityProfilesOperator.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-security-profiles-operator
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.securityProfilesOperator.url }}
  type: {{ .Values.helmRepository.securityProfilesOperator.type }}
{{- end }}
---
{{- if or .Values.vmLogs.enabled .Values.vmStack.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-victoriametrics
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  interval: {{ .Values.helmRepository.interval }}
  url: {{ .Values.helmRepository.victoriaMetrics.url }}
  type: {{ .Values.helmRepository.victoriaMetrics.type }}
{{- end }}
