apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-ns
  labels:
    {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  chart:
    spec:
      chart: raw
      interval: 3m
      sourceRef:
        kind: HelmRepository
        name: bedag
      version: 2.0.0
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  interval: .Values.helmRelease.interval
  values:
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: soperator
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: soperator-system
    
    {{- if .Values.mariadbOperator.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: mariadb-operator-system
    {{- end }}
    
    {{- if .Values.securityProfilesOperator.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: security-profiles-operator-system
    {{- end }}
    
    {{- if or .Values.vmLogs.enabled .Values.opentelemetry.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: logs-system
    {{- end }}
    
    {{- if or .Values.vmStack.enabled .Values.prometheusOperator.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring-system
    {{- end }}
    
    {{- if .Values.certManager.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager-system
    {{- end }}
    
    {{- if .Values.k8up.enabled }}
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: k8up-system
    {{- end }}
