{{- if .Values.prometheusOperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-prometheus-operator-crds
  labels:
  {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  chart:
    spec:
      chart: prometheus-operator-crds
      interval: {{ .Values.prometheusOperator.interval }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "soperator-fluxcd.fullname" . }}-prometheus-operator-crds
      version: {{ .Values.prometheusOperator.version }}
  interval: 60m
{{- end }}
