{{- if .Values.vmLogs.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-vm-logs
  labels:
  {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  chart:
    spec:
      chart: victoria-logs-single
      interval: 3m
      sourceRef:
        kind: HelmRepository
        name: {{ include "soperator-fluxcd.fullname" . }}-vm-logs
      version: 0.9.*
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 3m
  releaseName: logs
  targetNamespace: logs-system
  timeout: 3m
  upgrade:
    crds: CreateReplace
  values:
  {{- if .Values.vmLogs.values }}
  values:
    {{- toYaml .Values.vmLogs.values | nindent 4 }}
  {{- end }}
  valuesFrom:
  - kind: ConfigMap
    name: vm-logs
    optional: true
    valuesKey: values.yaml
{{- end }}
