{{- if and .Values.observability.enabled .Values.observability.vmStack.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "soperator-fluxcd.fullname" . }}-vm-stack
  labels:
  {{- include "soperator-fluxcd.labels" . | nindent 4 }}
spec:
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      interval: {{ .Values.observability.vmStack.interval }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "soperator-fluxcd.fullname" . }}-victoriametrics
      version: {{ .Values.observability.vmStack.version }}
  dependsOn:
  - name: {{ include "soperator-fluxcd.fullname" . }}-ns
  {{- if .Values.certManager.enabled }}
  - name: {{ include "soperator-fluxcd.fullname" . }}-cert-manager
  {{- end }}
  - name: {{ include "soperator-fluxcd.fullname" . }}-victoria-metrics-operator-crds
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
      remediateLastFailure: true
  interval: {{ .Values.observability.vmStack.interval }}
  timeout: {{ .Values.observability.vmStack.timeout }}
  releaseName: {{ .Values.observability.vmStack.releaseName }}
  {{- if .Values.observability.vmStack.namespace }}
  targetNamespace: {{ .Values.observability.vmStack.namespace }}
  {{- end }}
  values:
  {{- if .Values.observability.vmStack.overrideValues }}
    {{- toYaml .Values.observability.vmStack.overrideValues | nindent 4 }}
  {{- else }}
      alertmanager:
        enabled: false
      crds:
        enabled: false
      defaultRules:
        groups:
          etcd:
            create: false
          vmcluster:
            create: false
        rules:
          KubeHpaMaxedOut:
            create: false
          KubeMemoryOvercommit:
            create: false
          TooHighChurnRate24h:
            create: false
          TooManyScrapeErrors:
            create: false
      grafana:
        enabled: true
        {{- if .Values.observability.vmStack.values.grafanaIni }}
        grafana.ini: {{- toYaml .Values.observability.vmStack.values.grafanaIni | nindent 10 }}
        {{- end }}
        assertNoLeakedSecrets: false
        plugins:
          - https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
          - victoriametrics-logs-datasource
        sidecar:
          dashboards:
            searchNamespace: {{- toYaml .Values.observability.vmStack.values.dashboardNamespaces | nindent 12 }}
          datasources:
            searchNamespace: {{- toYaml .Values.observability.vmStack.values.dashboardNamespaces | nindent 12 }}
      kube-state-metrics:
        prometheusScrape: false
        selfMonitor:
          enabled: true
        collectors:
          - pods
        vmServiceScrape:
          spec:
            endpoints:
              - honorLabels: true
                metricRelabelConfigs:
                  - action: labeldrop
                    regex: (uid|container_id|image_id)
                port: http
              - honorLabels: true
                metricRelabelConfigs:
                  - action: labeldrop
                    regex: (uid|container_id|image_id)
                port: metrics
            jobLabel: app.kubernetes.io/name
      kubeControllerManager:
        enabled: false
      kubeEtcd:
        enabled: false
      kubeProxy:
        enabled: false
        vmScrape:
          spec:
            endpoints:
              - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
                port: http-metrics
                scheme: http
            jobLabel: jobLabel
            namespaceSelector:
              matchNames:
                - kube-system
      kubeScheduler:
        enabled: false
      kubelet:
        enabled: true
      coreDns:
        enabled: false
      prometheus-node-exporter:
        enabled: true
      victoria-metrics-operator:
        admissionWebhooks:
          enable: true
        crd:
          cleanup:
            enabled: false
          create: false
        operator:
          disable_prometheus_converter: false
          enable_converter_ownership: true
      vmagent:
        spec:
          {{- if .Values.observability.vmStack.publicEndpointEnabled }}
          remoteWriteSettings:
            label:
              container_id: {{ .Values.observability.vmStack.projectId  }}
            {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.remoteWriteSettings }}
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.remoteWriteSettings | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.remoteWriteSettings }}
          remoteWriteSettings:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.remoteWriteSettings | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.observability.vmStack.publicEndpointEnabled }}
          remoteWrite:
            - url: https://write.monitoring.eu-north1.nebius.cloud/projects/{{ .Values.observability.vmStack.projectId }}/buckets/soperator/prometheus
              inlineUrlRelabelConfig:
                - action: labeldrop
                  regex: feature_node_kubernetes_io_.*|kubernetes_io_.*|nvidia_com_gpu.*
                - action: labeldrop
                  regex: UUID|DCGM_FI_PROCESS_NAME|pci_bus_id|prometheus|DCGM_FI_DEV_SERIAL|DCGM_FI_DEV_NAME|job
            {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.remoteWrite }}
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.remoteWrite | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.remoteWrite }}
          remoteWrite:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.remoteWrite | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.observability.vmStack.publicEndpointEnabled }}
          volumeMounts:
            - name: tsa-token
              mountPath: /mnt/cloud-metadata/tsa-token
              readOnly: true
            {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.volumeMounts }}
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.volumeMounts | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.volumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.observability.vmStack.publicEndpointEnabled }}
          volumes:
            - name: tsa-token
              hostPath:
                path: /mnt/cloud-metadata/tsa-token
                type: File
            {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.volumes }}
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.volumes | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.volumes }}
          volumes:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.volumes | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if .Values.observability.vmStack.publicEndpointEnabled }}
          extraArgs:
            remoteWrite.flushInterval: 2s
            remoteWrite.bearerTokenFile: /mnt/cloud-metadata/tsa-token
            remoteWrite.maxRowsPerBlock: "12000"
            {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.extraArgs }}
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.extraArgs | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.extraArgs }}
          extraArgs:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.extraArgs | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.resources }}
          resources:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.resources | nindent 12 }}
          {{- end }}

          {{- if and .Values.observability.vmStack.values .Values.observability.vmStack.values.vmagent .Values.observability.vmStack.values.vmagent.spec .Values.observability.vmStack.values.vmagent.spec.extraEnv }}
          extraEnv:
            {{- toYaml .Values.observability.vmStack.values.vmagent.spec.extraEnv | nindent 12 }}
          {{- end }}
          
      vmalert:
        enabled: false
      vmsingle: {{ toYaml .Values.observability.vmStack.values.vmsingle | nindent 8 }}
  {{- end }}
  valuesFrom:
  - kind: ConfigMap
    name: terraform-victoria-metrics-operator
    optional: true
    valuesKey: values.yaml
  - kind: ConfigMap
    name: victoria-metrics-operator
    optional: true
    valuesKey: values.yaml
{{- end }}
