apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: soperatorchecks
  namespace: flux-system
spec:
  type: "oci"
  interval: 120m
  url: oci://cr.eu-north1.nebius.cloud/soperator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soperatorchecks
  namespace: flux-system
spec:
  dependsOn:
    - name: soperator
  releaseName: soperatorchecks
  interval: 3m
  timeout: 3m
  install:
    remediation:
      retries: 3
  targetNamespace: soperator-system
  chart:
    spec:
      chart: helm-soperatorchecks
      sourceRef:
        kind: HelmRepository
        name: soperatorchecks
      interval: 3m
  valuesFrom:
    - kind: ConfigMap
      name: soperatorchecks
      valuesKey: values.yaml
      optional: true
