name: E2E test soperator

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      terraform_repo:
        description: "terraform repository with slurm cluster deployment"
        required: true
        default: "nebius/nebius-solution-library"
        type: string
      terraform_repo_ref:
        description: "ref of terraform repo to apply"
        required: true
        default: "release/soperator"
        type: string
      path_to_installation:
        description: "path inside terraform repo to terraform module to apply"
        required: true
        default: "/soperator/installations/example"
        type: string
          

permissions:
  contents: read

concurrency:
  group: global-lock
  cancel-in-progress: false

jobs:
  e2e-test:
    runs-on: 
     - e2e-tests

    environment: e2e

    env:
      PATH_TO_INSTALLATION: "${{ github.workspace }}/terraform-repo/${{ github.event.inputs.path_to_installation || '/soperator/installations/example' }}"
      TERRAFORM_REPO: "${{ github.event.inputs.terraform_repo || 'nebius/nebius-solution-library' }}"
      TERRAFORM_REPO_REF: "${{ github.event.inputs.terraform_repo_ref || 'release/soperator' }}"
      NEBIUS_TENANT_ID: ${{ vars.E2E_TEST_NEBIUS_TENANT_ID }}
      NEBIUS_PROJECT_ID: ${{ vars.E2E_TEST_NEBIUS_PROJECT_ID }}
      NEBIUS_REGION: ${{ vars.E2E_TEST_NEBIUS_REGION }}
      INFINIBAND_FABRIC: ${{ vars.E2E_TEST_INFINIBAND_FABRIC }}
      SSH_KEYS: ${{ vars.E2E_TEST_SSH_KEYS }}
      O11Y_ACCESS_TOKEN: ${{ secrets.E2E_O11Y_ACCESS_TOKEN }}
      OUTPUT_LOG_FILE: "${{ github.workspace }}/output/output.log"
      OUTPUT_ERR_FILE: "${{ github.workspace }}/output/output.err"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install GO
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'

      - name: Checkout Terraform repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ env.TERRAFORM_REPO }}
          ref: ${{ env.TERRAFORM_REPO_REF }}
          path: "${{ github.workspace }}/terraform-repo"

      - name: Run Terratest
        run: |
          cd ${{ env.PATH_TO_INSTALLATION }}
          source .envrc
          cd -

          go test -v -timeout 2h --tags=e2e ./test/e2e/...

      - name: Add errors output to job summary
        if: ${{ always() }}
        run: cat $OUTPUT_ERR_FILE >> $GITHUB_STEP_SUMMARY

      - name: Upload terraform output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: "${{ github.workspace }}/output"
