name: E2E test soperator

on:
  workflow_dispatch:
    inputs:
      terraform_repo:
        description: "terraform repository with slurm cluster deployment"
        required: true
        default: "https://github.com/nebius/nebius-solution-library.git"
        type: string
      terraform_repo_version:
        description: "version of terraform to apply"
        required: true
        default: "release/soperator"
        type: string
      path_to_installation:
        description: "path inside terraform repo to terraform module to apply"
        required: true
        default: "/soperator/installations"
        type: string
          

permissions:
  contents: read

concurrency:
  group: global-lock
  cancel-in-progress: false

jobs:
  e2e-test:
    runs-on: 
     - self-hosted
     - e2e-tests

    env:
      PATH_TO_INSTALLATION: "${{ github.workspace }}terraform-repo/${{ github.event.inputs.path_to_installation }}"
      TERRAFORM_REPO: "${{ github.event.inputs.terraform_repo }}"
      TERRAFORM_REPO_VERSION: "${{ github.event.inputs.terraform_repo_version }}"
      NEBIUS_TENANT_ID: ${{ vars.E2E_TEST_NEBIUS_TENANT_ID }}
      NEBIUS_PROJECT_ID: ${{ vars.E2E_TEST_NEBIUS_PROJECT_ID }}
      NEBIUS_REGION: ${{ vars.E2E_TEST_NEBIUS_REGION }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install GO
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
            go-version-file: 'go.mod'

      - name: Checkout Terraform repository
        run: |
          git clone --branch "${{ env.TERRAFORM_REPO_VERSION }}" "${{ env.TERRAFORM_REPO }}" terraform-repo
          
          cd terraform-repo/${{ github.event.inputs.path_to_installation }}
          source .envrc

      # TODO: add clean-up step before run e2e (in case previous run didn't clean up)
      - name: Run Terratest
        run: |
          go test -v -timeout 2h --tags=e2e ./test/e2e/...
