name: E2E test soperator

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: global-lock
  cancel-in-progress: false

jobs:
  e2e-test:
    runs-on: 
     - self-hosted
     - e2e-tests

    env:
      TERRAFORM_REPO: "https://github.com/nebius/nebius-solution-library.git"
      TERRAFORM_BRANCH: "release/soperator"
      PATH_TO_TERRAFORM: "${{ github.workspace }}/nebius-solution-library/soperator/modules/slurm"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install GO
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
            go-version-file: 'go.mod'

      - name: Checkout Terraform repository
        run: |
          git clone --branch "${{ env.TERRAFORM_BRANCH }}" "${{ env.TERRAFORM_REPO }}" nebius-solution-library

      # TODO: add clean-up step before run e2e (in case previous run didn't clean up)

      - name: Run Terratest
        run: |
          go test -v ./test/e2e
