name: Build gpubench only

on:
  push:
    paths:
      - 'images/worker/gpubench/**'

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  pre-build:
    runs-on: self-hosted

    outputs:
      UNSTABLE: ${{ steps.set-env.outputs.unstable }}
  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Set environment to global output variables based on branch
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "unstable=false" >> $GITHUB_OUTPUT
          else
            echo "unstable=true" >> $GITHUB_OUTPUT
          fi

      - name: Print UNSTABLE from output
        run: |
          echo "Branch is - ${{ github.ref }}"
          echo "UNSTABLE - ${{ steps.set-env.outputs.unstable }}"
  gpubench_only:
    runs-on: self-hosted
    needs: pre-build

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install GO
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
            go-version-file: 'go.mod'

      - name: Check if version synced
        run: make test-version-sync

      - name: Run gpu bench tests
        run: |
          echo "Running gpubench tests"
          cd ./images/worker/gpubench/
          go test
