---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check labels
    runs-on: [self-hosted, X64]
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: feat,feature,test,fix,bug,dependencies,deps,doc,docs,documentation,other,ignore-for-release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
